[package]
name = "jrepl"
version = "0.1.0"
edition = "2024"

[dependencies]
reedline = "0.40.0"
serde_json = "1.0.140"
serde = "1.0.219"
clap = { version = "4.5.41", features = ["derive"] }
regex = "1.11.1"
